model: omgsr_f_512
seed: 123
flux_path: black-forest-labs/FLUX.1-dev
fixed_prompt: ""   # empty prompt is ok!
fixed_prompt_path: null
dataset_txt_or_dir_paths: []

vae_lora_rank: 64
flux_transformer_lora_rank: 64

# DINOv3-convnext
# 'tiny': 'dinov3_convnext_tiny_pretrain_lvd1689m-21b726bb.pth',
# 'small': 'dinov3_convnext_small_pretrain_lvd1689m-296db49d.pth',
# 'base': 'dinov3_convnext_base_pretrain_lvd1689m-801f2ba9.pth',
# 'large':'dinov3_convnext_large_pretrain_lvd1689m-61fa432d.pth',
# DINOv3-vit
# "dinov3_vits16": "dinov3_vits16_pretrain_lvd1689m-08c60483.pth",
# "dinov3_vits16plus": "dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth",
# "dinov3_vitb16": "dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth",
# "dinov3_vitl16": "dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth",
# "dinov3_vith16plus": "dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth",
# "dinov3_vit7b16": "dinov3_vit7b16_pretrain_lvd1689m-a955f4ea.pth"

dino_convnext_size: large        # tiny, small, base, large
dinov3_vit_size: dinov3_vitb16   # dinov3_vits16, dinov3_vits16plus, dinov3_vitb16, dinov3_vitl16, dinov3_vith16plus, dinov3_vit7b16
lambda_gan: 0.5
lambda_ldr: 5
lambda_dists: 5
mid_timestep: 173  # OK!

output_dir: ./trainings/omgsr_f_512
resolution: 512
train_batch_size: 1
max_train_steps: 50000
checkpointing_steps: 1000
save_img_steps: 100
resume_from_checkpoint: null
gradient_accumulation_steps: 4
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False
learning_rate: 5e-5
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-4
adam_epsilon: 1e-08
max_grad_norm: 1.0
logging_dir: logs
allow_tf32: False
mixed_precision: bf16


