model: omgsr_s_512
seed: 123
sd_path: stabilityai/sd-turbo
fixed_prompt: "A high-resolution, 8K, ultra-realistic image with sharp focus, vibrant colors, and natural lighting."
fixed_prompt_path: null
dataset_txt_or_dir_paths: []

vae_lora_rank: 16
unet_lora_rank: 32

cv_type: dinov3   # dino, dinov2, dinov3
lambda_gan: 0.5
lambda_mse: 2
lambda_lpips: 5
lambda_ldr: 5
lambda_ea_dists: 5
mid_timestep: 195

output_dir: ./trainings/omgsr_s_512
resolution: 512
train_batch_size: 1
max_train_steps: 50000
checkpointing_steps: 1000
save_img_steps: 100
resume_from_checkpoint: null
gradient_accumulation_steps: 4
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
learning_rate: 5e-5
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-4
adam_epsilon: 1e-08
max_grad_norm: 1.0
logging_dir: logs
allow_tf32: False
mixed_precision: bf16


