model: omgsr_q_512
seed: 123
qwen_image_path: Qwen/Qwen-Image
fixed_prompt: ""   # empty prompt is ok!
fixed_prompt_path: null
dataset_txt_or_dir_paths: []

vae_lora_rank: 4
qwen_transformer_lora_rank: 4

cv_type: dinov3   # dino, dinov2, dinov3
lambda_gan: 0.5
lambda_mae: 2
lambda_ldr: 5
lambda_dists: 5
mid_timestep: 173  # OK!

output_dir: ./trainings/omgsr_q_512
resolution: 512
train_batch_size: 1
max_train_steps: 50000
checkpointing_steps: 1000
save_img_steps: 100
resume_from_checkpoint: null
gradient_accumulation_steps: 4
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False
learning_rate: 2e-5
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-4
adam_epsilon: 1e-08
max_grad_norm: 1.0
logging_dir: logs
allow_tf32: False
mixed_precision: bf16


