model: omgsr_s_512
seed: 123
sd_path: stabilityai/stable-diffusion-2-1
fixed_prompt: ""   # empty prompt is ok!
fixed_prompt_path: null
dataset_txt_or_dir_paths: []

vae_lora_rank: 16
unet_lora_rank: 32

dinov3_convnext_size: large      # tiny, small, base, large
lambda_LRR: 5
lambda_Dv3D: 5
lambda_L1: 0.5
lambda_GAN: 0.5
mid_timestep: 273  

output_dir: ./omgsr_trainings/omgsr_s_512
resolution: 512
train_batch_size: 1
max_train_steps: 6000
checkpointing_steps: 1000
save_img_steps: 100
resume_from_checkpoint: null
gradient_accumulation_steps: 4
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: False
learning_rate: 5e-5
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-4
adam_epsilon: 1e-08
max_grad_norm: 1.0
logging_dir: logs
allow_tf32: False
mixed_precision: fp16


